apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  labels:
    app: demo-app
    # aadpodidbinding: <value>
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
        # aadpodidbinding: <value>
    spec:
      containers:
      - name: demo-app
        image: #{azureContainerRegistry}#/#{imageName}#:#{Build.BuildId}#
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi    
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet: 
            path: /weatherforecast
            port: 80
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
            path: /weatherforecast
            port: 80
          initialDelaySeconds: 15
        env:
          - name: CONFIG_EXAMPLE 
            valueFrom:
              configMapKeyRef:
                name: demo-app-configmap           
                key: configKey   
